language: cpp
sudo: required
compiler:
  - clang
os:
  - linux
git:
  depth: 3
python: 2.7.10
addons:
  apt:
    packages:
      - cmake
      - python-numpy
      - libboost1.55-all-dev
# before_install:
#   # - pip install --upgrade --user pip
#   # - pip install --user numpy
#   - sudo apt-get -qq update
#   - sudo apt-get install -y
#     python-numpy
#     libboost1.55-all-dev
script:
  cd build && cmake . && make -j2 && make test
