sudo: false
language: cpp
compiler:
  - clang
  # - g++
os:
  - linux
git:
  depth: 3
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - pythonxy-devel
    packages:
      - cmake
      - gcc-4.9
      - g++-4.9
      - libboost1.55-all-dev
      - python-numpy
before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install numpy --user `whoami`

script:
  cd build && cmake . && make -j2 && make test
