# Copyright Hans Dembinski 2019.
#
# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Based on original work by Antony Polukhin, see https://svn.boost.org/trac/boost/wiki/TravisCoverals

dist: xenial

branches:
  only:
    - master
    - develop

matrix:
  fast_finish: true

  include:
    - name: osx and standalone cmake
      os: osx
      language: cpp
      before_script:
        - mkdir build
        - cd build
        - cmake ..
      script:
        ctest -j2 --output-on-failure

    - name: osx and superproject cmake and b2 minimal
      os: osx
      language: cpp
      before_script:
        # clone minimal set of Boost libraries
        - cd ..
        - git clone -b $TRAVIS_BRANCH --depth 5 https://github.com/boostorg/boost.git
        - cd boost
        - git submodule update --init --depth 5 tools/boostdep

        # replace library with this version and install dependencies
        - rm -rf libs/histogram
        - mv $TRAVIS_BUILD_DIR libs/histogram

        # ignore optional dependencies not currently supported by the cmake build
        - python tools/boostdep/depinst/depinst.py --git_args "--depth 5 --jobs 3" histogram -N accumulators -N range -N serialization -N units

        # WORKAROUND: throw_exception tests have dependencies that depinst.py misses
        - python tools/boostdep/depinst/depinst.py --git_args "--depth 5 --jobs 3" throw_exception

      script:
        mkdir build && cd build &&
        cmake -DBOOST_ENABLE_CMAKE=1 -DBoost_VERBOSE=1 .. &&
        ctest -j2 --output-on-failure -R boost_histogram &&
        cd .. &&
        ./bootstrap.sh &&
        ./b2 headers &&
        ./b2 -q -j2 warnings-as-errors=on cxxstd=latest libs/histogram/test//minimal

    - os: linux
      language: python
      python: "3.6"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-8
      before_script:
        # clone minimal set of Boost libraries
        - cd ..
        - git clone -b $TRAVIS_BRANCH --depth 5 https://github.com/boostorg/boost.git
        - cd boost
        - git submodule update --init --depth 5 tools/build tools/boostdep

        # replace library with this version and install dependencies
        - rm -rf libs/histogram
        - mv $TRAVIS_BUILD_DIR libs/histogram
        - python3 tools/boostdep/depinst/depinst.py --git_args "--depth 5 --jobs 3" histogram

        # prepare build
        - ./bootstrap.sh
        - ./b2 headers
        - cd libs/histogram
        - B2="../../b2 -q -j2 warnings-as-errors=on"

        - pip install cpp-coveralls
      script:
        # don't compile examples in coverage build, coverage must come from tests alone
        $B2 toolset=gcc-5 cxxstd=14 exception-handling=off rtti=off test//minimal &&
        $B2 toolset=gcc-5 cxxstd=14 test//all examples &&
        $B2 toolset=gcc-8 cxxstd=latest coverage=on test//all &&
        GCOV=gcov-8 tools/cov.sh

notifications:
  email: false
