language: cpp
sudo: required
compiler:
  - clang
os:
  - linux
git:
  depth: 3
python: 2.7.10
before_install:
  # - pip install --upgrade --user pip
  # - pip install --user numpy
  - sudo apt-get install
    python-numpy
    libboost1.55-all-dev
script:
  cd build && cmake . && make -j2 && make test
