# Copyright Hans P. Dembinski 2016-2017
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

sudo: false

cache:
  pip: true

language: cpp

branches:
  except:
    - html

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-4.8
            - libboost1.55-dev
            - libboost-iostreams1.55
            - libboost-iostreams1.55-dev
            - libboost-python1.55
            - libboost-python1.55-dev
            - libboost-serialization1.55.0
            - libboost-serialization1.55-dev
      env: COMPILER_VERSION=4.8 CMAKE_BUILD_TYPE=cov
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - boost-latest
          packages:
            - clang-3.6
            - libboost1.55-dev
            - libboost-iostreams1.55
            - libboost-iostreams1.55-dev
            - libboost-python1.55
            - libboost-python1.55-dev
            - libboost-serialization1.55.0
            - libboost-serialization1.55-dev
      env: COMPILER_VERSION=3.6
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - boost-latest
          packages:
            - clang-3.6
            - libboost1.55-dev
            - libboost-iostreams1.55
            - libboost-iostreams1.55-dev
            - libboost-python1.55
            - libboost-python1.55-dev
            - libboost-serialization1.55.0
            - libboost-serialization1.55-dev
      env: COMPILER_VERSION=3.6 PYTHON_VERSION=2.7.3 NUMPY_SUPPORT=ON

git:
  depth: 1

# Install packages
install:
  - export CXX=${CXX}-${COMPILER_VERSION}
  - export CC=${CC}-${COMPILER_VERSION}
  - if [ -z ${PYTHON_VERSION} ]; then
      export BUILD_PYTHON=OFF;
    else
      export BUILD_PYTHON=ON;
    fi
  - if [ -z ${NUMPY_SUPPORT} ]; then
      export NUMPY_SUPPORT=OFF;
    fi
  - if [ "${CMAKE_BUILD_TYPE}" = "cov" ]; then
      pip install --user numpy==1.11.1 cpp-coveralls urllib3[secure];
    fi
  - if [ "${BUILD_NUMPY_SUPPORT}" = "ON" ]; then
      pip install --user numpy==1.11.1;
    fi

script:
  - travis_retry git clone --depth 1 https://github.com/boostorg/core.git core || exit 1
  - rsync --recursive core/include/boost/* include/boost/

  - cd build
  - if [ "${CMAKE_BUILD_TYPE}" = "cov" ]; then
      cmake . -DBUILD_PYTHON=OFF
              -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} &&
      make -j2 &&
      ctest -V;
      cmake . -DBUILD_PYTHON=ON
              -DBUILD_NUMPY_SUPPORT=OFF
              -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} &&
      make -j2 &&
      ctest -V;
      cmake . -DBUILD_PYTHON=ON
              -DBUILD_NUMPY_SUPPORT=ON
              -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} &&
      make -j2 &&
      ctest -V;
    else
      cmake . -DBUILD_PYTHON=${BUILD_PYTHON}
              -DPYTHON_VERSION=${PYTHON_VERSION}
              -DBUILD_NUMPY_SUPPORT=${BUILD_NUMPY_SUPPORT}
              -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} &&
      make -j2 &&
      ctest -V;
    fi

# Calculate coverage
after_success:
  if [ "${CMAKE_BUILD_TYPE}" = "cov" ]; then
    coveralls -r .. -b . --gcov=`which gcov-${COMPILER_VERSION}`;
  fi

after_failure:
  # - printf "r\nbt" > gdb.cmd
  # - gdb axis_test --batch -x gdb.cmd

notifications:
  email: false
