language: cpp
env:
  - USE_PYTHON=ON USE_NUMPY=ON COVERAGE=ON
  - USE_PYTHON=ON USE_NUMPY=ON COVERAGE=OFF
  - USE_PYTHON=ON USE_NUMPY=OFF COVERAGE=OFF
  - USE_PYTHON=OFF USE_NUMPY=OFF COVERAGE=OFF
matrix:
  exclude:
    - compiler: clang
      env: USE_PYTHON=ON USE_NUMPY=ON COVERAGE=ON
compiler:
  - clang
  - gcc
os:
  - linux
git:
  depth: 3
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      # - gcc-4.9
      # - g++-4.9
      - libboost1.55-all-dev

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda install --yes numpy
  - pip install --user cpp-coveralls
  # - conda install --yes -c dan_blanchard python-coveralls nose-cov

script:
  cd build && 
  cmake . -DUSE_PYTHON=${USE_PYTHON}
          -DUSE_NUMPY=${USE_NUMPY} -DCOVERAGE=${COVERAGE} &&
  make -j2 &&
  make test

# Calculate coverage
after_success:
  - if [ "${COVERAGE}" = "ON" ]; then coveralls -r .. -b . --verbose; fi
