language: cpp
compiler:
  - clang
os:
  - linux
git:
  depth: 3
python: 2.7.10
before_install:
  - pip install --user --upgrade pip
  - pip install --user numpy
script:
  cd build && cmake . && make -j2 && make test
