language: cpp
sudo: false
compiler:
  - clang
  - g++
os:
  - linux
git:
  depth: 3
python: 2.7.10
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-4.9
      - g++-4.9
      - python-numpy
      - libboost1.55-all-dev
before_install:
  - pip install --upgrade pip
  - pip install --user numpy

script:
  cd build && cmake . && make -j2 && make test
