language: cpp
env:
  - PYTHON_VERSION=3 USE_PYTHON=ON USE_NUMPY=ON COVERAGE=ON CC=gcc CXX=g++
  - PYTHON_VERSION=2 USE_PYTHON=ON USE_NUMPY=ON COVERAGE=ON CC=gcc CXX=g++
  - PYTHON_VERSION=3 USE_PYTHON=ON USE_NUMPY=ON COVERAGE=OFF
  - PYTHON_VERSION=2 USE_PYTHON=ON USE_NUMPY=ON COVERAGE=OFF
  - PYTHON_VERSION=2 USE_PYTHON=ON USE_NUMPY=OFF COVERAGE=OFF
  - PYTHON_VERSION=2 USE_PYTHON=OFF USE_NUMPY=OFF COVERAGE=OFF
compiler:
  - clang
os:
  - linux
git:
  depth: 10
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-all-dev

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda create --name pyenv --yes python=${PYTHON_VERSION} numpy
  - source activate pyenv
  - pip install --user cpp-coveralls

script:
  cd build && 
  cmake . -DUSE_PYTHON=${USE_PYTHON}
          -DUSE_NUMPY=${USE_NUMPY}
          -DCOVERAGE=${COVERAGE} &&
  make -j2 &&
  ctest -V

# Calculate coverage
after_success:
  - if [ "${COVERAGE}" = "ON" ]; then coveralls -r .. -b . --verbose; fi

after_failure:
  - make clean && VERBOSE=1 make

notifications:
  email:
    on_success: change
