sudo: false
language: cpp
compiler:
  - clang
  # - g++
  # - g++-4.9
os:
  - linux
git:
  depth: 3
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      # - cmake
      # - gcc-4.9
      # - g++-4.9
      - libboost1.55-all-dev

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda install --yes numpy nose
  - pip install --user cpp-coveralls
  # - conda install --yes -c dan_blanchard python-coveralls nose-cov

script:
  cd build && cmake . -DCOVERAGE=ON && make -j2 && make test

# Calculate coverage
after_success:
  - coveralls
