language: cpp
env:
  - USE_PYTHON=ON USE_NUMPY=ON COVERAGE=ON CC=gcc CXX=g++
  - USE_PYTHON=ON USE_NUMPY=ON COVERAGE=OFF
  - USE_PYTHON=ON USE_NUMPY=OFF COVERAGE=OFF
  - USE_PYTHON=OFF USE_NUMPY=OFF COVERAGE=OFF
compiler:
  - clang
os:
  - linux
git:
  depth: 3
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-all-dev

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda install --yes numpy
  - pip install --user cpp-coveralls

script:
  cd build && 
  cmake . -DUSE_PYTHON=${USE_PYTHON}
          -DUSE_NUMPY=${USE_NUMPY}
          -DCOVERAGE=${COVERAGE} &&
  make -j2 &&
  ctest -V

# Calculate coverage
after_success:
  - if [ "${COVERAGE}" = "ON" ]; then coveralls -r .. -b . --verbose; fi

notifications:
  email:
    on_success: change
