# Copyright 2017 Hans Dembinski
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

shallow_clone: true

branches:
  only:
    - master
    - develop

build: off

test_script:
  - cd build
  - cmake . -DCMAKE_BUILD_TYPE=debug
  - make -j2
  - ctest -V
